//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBlog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.PostTag = new HashSet<PostTag>();
        }
    
        public int PostID { get; set; }
        public Nullable<int> LangID { get; set; }
        public Nullable<int> TechID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Topic { get; set; }
        public string RawPost { get; set; }
    
        public virtual Lang Lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostTag> PostTag { get; set; }
        public virtual Technology Technology { get; set; }
    }
}
